# Generated by Django 4.1.6 on 2023-02-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=1000)),
                ('image_url', models.URLField()),
                ('email', models.EmailField(max_length=256)),
                ('location', models.CharField(max_length=1000)),
                ('local_pharmacy', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=200)),
                ('date_prescribed', models.CharField(max_length=50)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbayapi.physician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbayapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='physician',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbayapi.user'),
        ),
    ]
